# 顶级必要的配置参数
Name = "DongKongEndpoint"
RpcAddress = "0.0.0.0:5570"
Broadcast = false

# 东控主板配置参数
[BoardOptions]
  serialNumber = 123456
  doorCount = 4

# Socket客户端配置参数
[SocketClientOptions]
  remoteAddress = "board.dongk.edgex.io:60000"
  readTimeout = "1s"
  writeTimeout = "1s"