# 顶级必要的配置参数
Name = "DongKongEndpoint"
RpcAddress = "0.0.0.0:5570"
Broadcast = false

# 东控主板配置参数
[BoardOptions]
  serialNumber = 223177933
  doorCount = 2

# Socket客户端配置参数
[SocketClientOptions]
  remoteAddress = "192.168.1.50:60000"
  readTimeout = "1s"
  writeTimeout = "1s"