sudo: required
language: go
go:
  - "1.12.4"
dist: bionic

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

env:
  - DOCKER_CLI_EXPERIMENTAL=enabled
  - GOMAXPROCS=4 GO111MODULE=on

install:
  - sudo apt update -y && sudo apt install upx -y

before_script:
  # Login Aliyun Registry
  - echo "$DOCKER_PASSWORD" | sudo docker login registry.cn-shenzhen.aliyuncs.com -u "$DOCKER_USERNAME" --password-stdin

script:
  - go mod download
  - sudo ./build.sh

branches:
  only:
    - master