NodeName = "WiegandTrigger"
Topic = "wiegand/events"

# 主板配置参数
[BoardOptions]
  serialNumber = 123456
  doorCount = 4

# SocketServer配置参数
[SocketServerOptions]
  address = [
      "udp://0.0.0.0:5570"
  ]